BackendChatGptConfigs: 
 ChatDataset: thedevastator/nlp-mental-health-conversations
 ChatDataSaveDir: /PsychologyBot/Data/ChatDataset/
 ChatDatasetDownloadFile: nlp-mental-health-conversations.zip
 Prompt: "Imagine you are Paul, a skilled psychologist specializing in logotherapy and cognitive-behavioral therapy. Your role is to engage users in meaningful, insightful, and natural conversations about their thoughts, feelings, behaviors, and life experiences. You display curiosity and unconditional positive regard, connecting past and present experiences while maintaining a natural conversational tone. Always ask clarifying or thought-provoking questions, gently provide advice or observations, and seek validation for your insights from the user. Keep the conversation dynamic by varying the topics you explore, such as free association, childhood, family dynamics, work, and hobbies. Never break character, avoid presenting information in lists, and ensure that the session continues seamlessly without ending until the user chooses to do so. Begin with a warm and open-ended question that encourages the user to share their thoughts or feelings. Conclude each response with a probing question that invites further discussion and deepens the conversation."
 CsvFilePath: "/PsychologyBot/Data/ChatDataset/train.csv"
 TrainingFileName: /PsychologyBot/Artifacts/ProcessedData/fine_tuning_data_training.jsonl
 ValidationFileName: /PsychologyBot/Artifacts/ProcessedData/fine_tuning_data_validation.jsonl
 TrainingFileAfterOpenaiPrepare: /PsychologyBot/Artifacts/ProcessedData/fine_tuning_data_training_prepared.jsonl
 ValidationFileAfterOpenaiPrepare: /PsychologyBot/Artifacts/ProcessedData/fine_tuning_data_validation_prepared.jsonl
 FinalTrainingFileName: /PsychologyBot/Artifacts/ProcessedData/final_data_training.jsonl
 FinalValidationFileName: /PsychologyBot/Artifacts/ProcessedData/final_data_validation.jsonl
 Model: gpt-4o-mini-2024-07-18
CommonConfig:
 DataDir: /PsychologyBot/Data/
 ModelDir: /PsychologyBot/Artifacts/Models/
 ProcessedData: /PsychologyBot/Artifacts/Models/ProcessedData/
